name: Run Cypress Tests in Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, edge, electron]

    container: cypress/included:12.17.4  # Use any Cypress-included Docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }}
         
      - name: Upload screenshots (if any) (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots

      - name: Upload videos (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos

